version: "3.5"
services:
  wizbot:
    build: .
    #image: wizkiller96/wizbot
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - ./credentials.json:/app/credentials.json:ro
      - ./data:/app/data
    labels:
      "com.centurylinklabs.watchtower.enable": "true"
  redis:
    image: redis:alpine
    sysctls:
      net.core.somaxconn: 511

  #watchtower:
  #  image: v2tec/watchtower
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
  #  command: --interval 86400 --cleanup --label-enable