START TRANSACTION;
DROP TABLE excludeditem;

ALTER TABLE guildxpconfig DROP CONSTRAINT pk_guildxpconfig;

ALTER TABLE channelxpconfig DROP CONSTRAINT ak_channelxpconfig_guildid_channelid;

ALTER TABLE xpsettings DROP COLUMN serverexcluded;

ALTER TABLE guildxpconfig ALTER COLUMN xpamount TYPE bigint;

ALTER TABLE guildxpconfig ALTER COLUMN cooldown TYPE real;

ALTER TABLE guildxpconfig ADD id integer GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE guildxpconfig ADD ratetype integer NOT NULL DEFAULT 0;

ALTER TABLE channelxpconfig ALTER COLUMN xpamount TYPE bigint;

ALTER TABLE channelxpconfig ADD ratetype integer NOT NULL DEFAULT 0;

ALTER TABLE guildxpconfig ADD CONSTRAINT ak_guildxpconfig_guildid_ratetype UNIQUE (guildid, ratetype);

ALTER TABLE guildxpconfig ADD CONSTRAINT pk_guildxpconfig PRIMARY KEY (id);

ALTER TABLE channelxpconfig ADD CONSTRAINT ak_channelxpconfig_guildid_channelid_ratetype UNIQUE (guildid, channelid, ratetype);

INSERT INTO "__EFMigrationsHistory" (migrationid, productversion)
VALUES ('20250226215159_xp-rate-rework', '9.0.1');

COMMIT;

