START TRANSACTION;
ALTER TABLE userfishstats DROP COLUMN bait;

ALTER TABLE userfishstats DROP COLUMN pole;

ALTER TABLE userquest ALTER COLUMN progress TYPE integer;

CREATE TABLE userfishitem (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    userid numeric(20,0) NOT NULL,
    itemtype integer NOT NULL,
    itemid integer NOT NULL,
    isequipped boolean NOT NULL,
    usesleft integer,
    expiresat timestamp without time zone,
    CONSTRAINT pk_userfishitem PRIMARY KEY (id)
);

CREATE INDEX ix_userfishitem_userid ON userfishitem (userid);

INSERT INTO "__EFMigrationsHistory" (migrationid, productversion)
VALUES ('20250327001838_fishitems', '9.0.1');

COMMIT;

