START TRANSACTION;
CREATE TABLE livechannelconfig (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    guildid numeric(20,0) NOT NULL,
    channelid numeric(20,0) NOT NULL,
    template text NOT NULL,
    CONSTRAINT pk_livechannelconfig PRIMARY KEY (id)
);

CREATE INDEX ix_livechannelconfig_guildid ON livechannelconfig (guildid);

CREATE UNIQUE INDEX ix_livechannelconfig_guildid_channelid ON livechannelconfig (guildid, channelid);

INSERT INTO "__EFMigrationsHistory" (migrationid, productversion)
VALUES ('20250318160459_livechannels', '9.0.1');

COMMIT;

