START TRANSACTION;
ALTER TABLE userfishstats ADD bait integer;

ALTER TABLE userfishstats ADD pole integer;

CREATE TABLE channelxpconfig (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    guildid numeric(20,0) NOT NULL,
    channelid numeric(20,0) NOT NULL,
    xpamount integer NOT NULL,
    cooldown real NOT NULL,
    CONSTRAINT pk_channelxpconfig PRIMARY KEY (id),
    CONSTRAINT ak_channelxpconfig_guildid_channelid UNIQUE (guildid, channelid)
);

CREATE TABLE guildxpconfig (
    guildid numeric(20,0) NOT NULL,
    xpamount integer NOT NULL,
    cooldown integer NOT NULL,
    xptemplateurl text,
    CONSTRAINT pk_guildxpconfig PRIMARY KEY (guildid)
);

INSERT INTO "__EFMigrationsHistory" (migrationid, productversion)
VALUES ('20250225212147_xp-excl-xp-rate', '9.0.1');

COMMIT;

