START TRANSACTION;
CREATE TABLE linkfix (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    guildid numeric(20,0) NOT NULL,
    olddomain text NOT NULL,
    newdomain text NOT NULL,
    CONSTRAINT pk_linkfix PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ix_linkfix_guildid_olddomain ON linkfix (guildid, olddomain);

INSERT INTO "__EFMigrationsHistory" (migrationid, productversion)
VALUES ('20250322225824_linkfixer', '9.0.1');

COMMIT;

