START TRANSACTION;
CREATE TABLE xpexcludeditem (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    guildid numeric(20,0) NOT NULL,
    itemtype integer NOT NULL,
    itemid numeric(20,0) NOT NULL,
    CONSTRAINT pk_xpexcludeditem PRIMARY KEY (id),
    CONSTRAINT ak_xpexcludeditem_guildid_itemtype_itemid UNIQUE (guildid, itemtype, itemid)
);

CREATE INDEX ix_xpexcludeditem_guildid ON xpexcludeditem (guildid);

INSERT INTO "__EFMigrationsHistory" (migrationid, productversion)
VALUES ('20250318113819_xpexclusion', '9.0.1');

COMMIT;

