START TRANSACTION;
CREATE TABLE userquest (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    questnumber integer NOT NULL,
    userid numeric(20,0) NOT NULL,
    questid integer NOT NULL,
    progress bigint NOT NULL,
    iscompleted boolean NOT NULL,
    dateassigned timestamp without time zone NOT NULL,
    CONSTRAINT pk_userquest PRIMARY KEY (id)
);

CREATE INDEX ix_userquest_userid ON userquest (userid);

CREATE UNIQUE INDEX ix_userquest_userid_questnumber_dateassigned ON userquest (userid, questnumber, dateassigned);

INSERT INTO "__EFMigrationsHistory" (migrationid, productversion)
VALUES ('20250324230804_quests', '9.0.1');

COMMIT;

