$.getJSON('https://api.github.com/repos/wizkiller96/wizbot/commits', function (data) {
    $('#changes').html(
        '<tr><td class="body-item mbr-fonts-style display-7" scope="row"><strong>0</strong></td><td class="body-item mbr-fonts-style display-7">' + data[0].commit.author.name + '</td>' + '<td class="body-item mbr-fonts-style display-7"><a href="' + data[0].html_url + '">' + data[0].commit.message + '</a></td><td>' + data[0].commit.author.date + '</td></tr>' + 
        '<tr><td class="body-item mbr-fonts-style display-7" scope="row"><strong>1</strong></td><td class="body-item mbr-fonts-style display-7">' + data[1].commit.author.name + '</td>' + '<td class="body-item mbr-fonts-style display-7"><a href="' + data[1].html_url + '">' + data[1].commit.message + '</a></td><td>' + data[1].commit.author.date + '</td></tr>' + 
        '<tr><td class="body-item mbr-fonts-style display-7" scope="row"><strong>2</strong></td><td class="body-item mbr-fonts-style display-7">' + data[2].commit.author.name + '</td>' + '<td class="body-item mbr-fonts-style display-7"><a href="' + data[2].html_url + '">' + data[2].commit.message + '</a></td><td>' + data[2].commit.author.date + '</td></tr>' + 
        '<tr><td class="body-item mbr-fonts-style display-7" scope="row"><strong>3</strong></td><td class="body-item mbr-fonts-style display-7">' + data[3].commit.author.name + '</td>' + '<td class="body-item mbr-fonts-style display-7"><a href="' + data[3].html_url + '">' + data[3].commit.message + '</a></td><td>' + data[3].commit.author.date + '</td></tr>' + 
        '<tr><td class="body-item mbr-fonts-style display-7" scope="row"><strong>4</strong></td><td class="body-item mbr-fonts-style display-7">' + data[4].commit.author.name + '</td>' + '<td class="body-item mbr-fonts-style display-7"><a href="' + data[4].html_url + '">' + data[4].commit.message + '</a></td><td>' + data[4].commit.author.date + '</td></tr>' + 
        '<tr><td class="body-item mbr-fonts-style display-7" scope="row"><strong>5</strong></td><td class="body-item mbr-fonts-style display-7">' + data[5].commit.author.name + '</td>' + '<td class="body-item mbr-fonts-style display-7"><a href="' + data[5].html_url + '">' + data[5].commit.message + '</a></td><td>' + data[5].commit.author.date + '</td></tr>' + 
        '<tr><td class="body-item mbr-fonts-style display-7" scope="row"><strong>6</strong></td><td class="body-item mbr-fonts-style display-7">' + data[6].commit.author.name + '</td>' + '<td class="body-item mbr-fonts-style display-7"><a href="' + data[6].html_url + '">' + data[6].commit.message + '</a></td><td>' + data[6].commit.author.date + '</td></tr>' + 
        '<tr><td class="body-item mbr-fonts-style display-7" scope="row"><strong>7</strong></td><td class="body-item mbr-fonts-style display-7">' + data[7].commit.author.name + '</td>' + '<td class="body-item mbr-fonts-style display-7"><a href="' + data[7].html_url + '">' + data[7].commit.message + '</a></td><td>' + data[7].commit.author.date + '</td></tr>'
          );
});